name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore NuGet packages
      run: dotnet restore ./UtcTimeAPI.sln

    - name: Build
      run: dotnet build ./UtcTimeAPI.sln --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish ./UtcTimeAPI.sln --configuration Release --no-build
